import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Heebo } from "next/font/google";
import Footer from "./components/Footer/Footer";

const mainFont = Heebo({
  variable: "--font-main",
  subsets: ["hebrew", "latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "GrouPay",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="he" dir="rtl">
      <body className={`${mainFont.variable} antialiased layoutRoot`}>
        <Providers>
          <main className="layoutMain">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
